### ISSUE TITLE
Getting error selecting folder trying to backup a GMail / Google Suite mailbox

### ISSUE THREAD

**Issue by petersasi** [ansemjo/imapfetch#61]
--list works:

```
<EMAIL ADDRESS>: INBOX
<EMAIL ADDRESS>: [Gmail]
<EMAIL ADDRESS>: [Gmail]/All Mail
<EMAIL ADDRESS>: [Gmail]/Bin
<EMAIL ADDRESS>: [Gmail]/Drafts
<EMAIL ADDRESS>: [Gmail]/Important
<EMAIL ADDRESS>: [Gmail]/Sent Mail
<EMAIL ADDRESS>: [Gmail]/Spam
<EMAIL ADDRESS>: [Gmail]/Starred
```

However if I try excluding INBOX* it fails with this error:
```
~$ .local/bin/imapfetch --full -vv settings.cfg
imapfetch: read configuration from settings.cfg
imapfetch: processing section <EMAIL ADDRESS>
<EMAIL ADDRESS>: connecting to imap.gmail.com
<EMAIL ADDRESS>: logging in as <EMAIL ADDRESS>
<EMAIL ADDRESS>: opened archive in /mnt/h/EmailArchive/<EMAIL ADDRESS>
<EMAIL ADDRESS>: excluded folder INBOX due to 'INBOX*'
<EMAIL ADDRESS>: processing folder [Gmail]
<EMAIL ADDRESS>: select failed: [NONEXISTENT] Unknown Mailbox: [Gmail] (Failure)
Traceback (most recent call last):
  File "/home/sape/.local/lib/python3.10/site-packages/imapfetch.py", line 342, in commandline
    mailserver.cd(folder)
  File "/home/sape/.local/lib/python3.10/site-packages/imapfetch.py", line 55, in cd
    return self.client.select_folder(folder, readonly=True)
  File "/home/sape/.local/lib/python3.10/site-packages/imapclient/imapclient.py", line 819, in select_folder
    self._command_and_check("select", self._normalise_folder(folder), readonly)
  File "/home/sape/.local/lib/python3.10/site-packages/imapclient/imapclient.py", line 1753, in _command_and_check
    self._checkok(command, typ, data)
  File "/home/sape/.local/lib/python3.10/site-packages/imapclient/imapclient.py", line 1759, in _checkok
    self._check_resp("OK", command, typ, data)
  File "/home/sape/.local/lib/python3.10/site-packages/imapclient/imapclient.py", line 1636, in _check_resp
    raise exceptions.IMAPClientError(
imaplib.IMAP4.error: select failed: [NONEXISTENT] Unknown Mailbox: [Gmail] (Failure)
imapfetch: encountered errors!
imapfetch: <EMAIL ADDRESS>: error('select failed: [NONEXISTENT] Unknown Mailbox: [Gmail] (Failure)')
```

Maybe escaping the imap select could help?
https://stackoverflow.com/questions/75395280/i-am-unable-to-retrieve-gmail-emails-from-any-other-labels-other-than-inbox-sent

**Comment by ansemjo** [comment]
Gmail is confusing. 😬
I can't open the `[Gmail]` inbox, no matter what I try. But all the Mail seems to be in the aptly named `[Gmail]/All Mail` anyway, which opens fine.

I've added the same compat tweaks that are needed for exchange and added some special handling for the `[Gmail]` folder itself, as well as any exclusion patterns that begin with this string. Otherwise, `[` and `]` are special characters and exclusion rules for Gmail would need to be written as `[[]Gmail[]]/Bin`.

Also note that an identical mail can be returned as different UIDs in different folders / labels on Gmail. These duplicates won't be stored; only the one occurence under which-ever label comes first will be saved.

Please recheck with the latest commit and reopen if you still encounter issues. :)
